Question1
What percentage of total hospital revenue is generated by each admission type?
Answer: 

select admission_type, sum(billingamount) as total_revenue,
round(
(sum(billingamount) * 100 / (select sum(billingamount) from healthcare.healthcare_patients)), 2) as revenue_percentage

from healthcare.healthcare_patients
group by admission_type
________________________________________
Question2
Which 3 medical conditions generate the highest total billing revenue?
Answer:

select medicalcondition, sum(billingamount) as Total_revenue
from healthcare.healthcare_patients
group by medicalcondition
order by Total_revenue DESC
limit 3
________________________________________
Question3
What percentage of total revenue comes from High Risk patients?
Answer:

select high_risk_patient_flag, sum(billingamount),
round(
sum(billingamount) * 100 / (select sum(billingamount) from healthcare.healthcare_patients), 2) as revenue_percentage
from healthcare.healthcare_patients
Group by high_risk_patient_flag
having high_risk_patient_flag = 'High Risk'
________________________________________
Question4
For each admission type, show:
•	average billing
•	difference from overall average billing
Answer:

select admission_type, ROUND(avg(billingamount), 2) as avg_billing,
Round(
((select avg(billingamount) from healthcare.healthcare_patients) - avg(billingamount)), 2)
as diff_from_overall
from healthcare.healthcare_patients
group by admission_type
________________________________________
Question5
Rank hospitals based on total billing revenue.


Answer:

select hospital,sum(billingamount), 
rank() over (order by sum(billingamount) desc) as revenue_rank
from healthcare.healthcare_patients
group by hospital
________________________________________
🧠 Task 6 — Top Doctor per Medical Condition
Question6
For each medical condition, find the doctor who treated the most patients.

Answer:

WITH 

doctor_condition_counts AS (
    SELECT
        medicalcondition,
        doctor,
        COUNT(*) AS patient_count
    FROM healthcare.healthcare_patients
    GROUP BY medicalcondition, doctor
),
ranked_doctors AS (
    SELECT
        medicalcondition,
        doctor,
        patient_count,
        RANK() OVER (
            PARTITION BY medicalcondition
            ORDER BY patient_count DESC
        ) AS doctor_rank
    FROM doctor_condition_counts
)
SELECT
    medicalcondition,
    doctor,
    patient_count
FROM ranked_doctors
WHERE doctor_rank = 1
ORDER BY medicalcondition;
________________________________________
Question7
Compare average length of stay between:
•	High Risk patients
•	Low Risk patients


Answer:
select high_risk_patient_flag, round(avg(lengthofstay), 2) as avg_los
from healthcare.healthcare_patients
group by high_risk_patient_flag________________________________________
Question8
Create revenue bands:
•	< 10000 → Low Revenue
•	10000–30000 → Medium Revenue
•	30000 → High Revenue
Then calculate:
| revenue_band | total_revenue |

Answer:
select
case
when billingamount < 10000 then 'Low Revenue'
when billingamount > 10000 and billingamount < 30000 then 'Medium Revenue'
else 'High Revenue'
end as revenue_band, round(sum(billingamount), 2) as total_revenue
from healthcare.healthcare_patients
group by revenue_band
________________________________________
Question9
Which 5 doctors treated the highest number of High Risk patients?
Answer:

select doctor, count(*) as high_risk_count
from healthcare.healthcare_patients
where high_risk_patient_flag = 'High Risk'
group by doctor
order by count(*) desc
limit 5
________________________________________
Question10
For each admission type, calculate:
•	total patients
•	total revenue
•	average length of stay


Answer:

select 
admission_type, 
count(*) as patient_count, 
round(sum(billingamount), 2) as total_revenue, 
round(avg(lengthofstay), 2) as avg_los
from healthcare.healthcare_patients
group by admission_type
order by count(*) desc
